#!/usr/bin/env python3
"""
Core validator implementation for validating Rust code.

Provides validation methods for:
- Compilation (cargo build)
- Linting (cargo clippy)
- UB detection (cargo miri)
- Concurrency testing (loom)
- Safety analysis (static analysis)
- Lock safety analysis (static analysis)
"""

import os
import re
import subprocess
import tempfile
import shutil
from typing import Dict, List, Tuple, Optional
from .errors import ErrorInfo, ValidationResult
from .tools import ValidationTool


class CodeValidator:
    """Validator for Rust code generated by refactor."""
    
    NIGHTLY = "nightly"
    COMPILE_TIMEOUT = 600  # seconds - 10 minutes for dependency download and compilation
    MIRI_TIMEOUT = 1800  # seconds - 30 minutes for miri (miri runs very slow: 5-15 min per example)
    LOOM_TIMEOUT = 3600  # seconds - 60 minutes for loom (loom can be very slow for complex code)
    
    # Regex patterns for parsing Rust compiler errors
    ERROR_PATTERN = re.compile(
        r'error(?:\[([^\]]+)\])?: (.+?)(?:\n\s*-->\s*(.+?):\s*(\d+):(\d+))?',
        re.MULTILINE
    )
    
    def __init__(self, deps_dir: Optional[str] = None):
        """
        Initialize validator.
        
        Args:
            deps_dir: Path to compiled dependencies (optional)
        """
        self.deps_dir = deps_dir or "/home/guoxy/concrat/deps_crate/target/debug/deps"
    
    # ════════════════════════════════════════════════════════════════════════
    # Error Parsing
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def parse_compile_errors(stderr: str) -> List[ErrorInfo]:
        """
        Parse Rust compiler errors from stderr into structured ErrorInfo objects.
        
        Handles formats like:
            error[E0425]: cannot find value `x` in this scope
             --> src/main.rs:5:21
        
        Returns:
            List of ErrorInfo objects
        """
        errors = []
        
        # Split by "error" lines and process each
        lines = stderr.split('\n')
        i = 0
        while i < len(lines):
            line = lines[i]
            
            if line.startswith('error'):
                # Parse error[CODE]: message format
                match = re.match(r'error(?:\[([^\]]+)\])?: (.+)$', line)
                if match:
                    error_code = match.group(1) or ""
                    message = match.group(2)
                    
                    # Look for location in next lines
                    location = ""
                    error_line = -1
                    error_col = -1
                    details = []
                    
                    i += 1
                    while i < len(lines) and lines[i].startswith(' '):
                        loc_match = re.match(r'\s*-->\s*(.+):(\d+):(\d+)', lines[i])
                        if loc_match:
                            location = loc_match.group(1)
                            error_line = int(loc_match.group(2))
                            error_col = int(loc_match.group(3))
                        else:
                            details.append(lines[i].strip())
                        i += 1
                    
                    errors.append(ErrorInfo(
                        error_type="compile_error",
                        message=message,
                        location=location,
                        error_code=error_code,
                        line=error_line,
                        column=error_col,
                        details="\n".join(details)
                    ))
                    continue
            
            i += 1
        
        return errors
    
    # ════════════════════════════════════════════════════════════════════════
    # Safety Metrics
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def count_pattern(code: str, pattern: str) -> int:
        """Count occurrences of a regex pattern in code."""
        return len(re.findall(pattern, code))
    
    @staticmethod
    def safety_metrics(code: str) -> Dict[str, int]:
        """Extract safety metrics from code."""
        return {
            "unsafe":       CodeValidator.count_pattern(code, r'\bunsafe\b'),
            "pthread":      CodeValidator.count_pattern(code, r'\bpthread_'),
            "raw_ptr":      CodeValidator.count_pattern(code, r'\*mut\b|\*const\b'),
            "static_mut":   CodeValidator.count_pattern(code, r'\bstatic\s+mut\b'),
            "libc":         CodeValidator.count_pattern(code, r'\blibc::'),
            "std_mutex":    CodeValidator.count_pattern(code, r'\bMutex\b'),
            "std_arc":      CodeValidator.count_pattern(code, r'\bArc\b'),
            "std_rwlock":   CodeValidator.count_pattern(code, r'\bRwLock\b'),
            "std_condvar":  CodeValidator.count_pattern(code, r'\bCondvar\b'),
            "std_thread":   CodeValidator.count_pattern(code, r'\bthread::spawn\b'),
            "lines":        len(code.splitlines()),
        }
    
    # ════════════════════════════════════════════════════════════════════════
    # Compilation Check
    # ════════════════════════════════════════════════════════════════════════
    
    def try_compile_with_cargo(self, rs_file: str, example_dir: str) -> Tuple[bool, List[ErrorInfo]]:
        """Try compiling a .rs file using the example's Cargo.toml context."""
        td = tempfile.mkdtemp()
        try:
            # Copy Cargo.toml and support files from the original example directory
            for f in ["Cargo.toml", "rust-toolchain"]:
                src = os.path.join(example_dir, f)
                if os.path.exists(src):
                    shutil.copy(src, td)
            
            # Copy c2rust-lib.rs - this contains module declarations (pub mod main;)
            lib_rs = os.path.join(example_dir, "c2rust-lib.rs")
            if not os.path.exists(lib_rs):
                # If c2rust-lib.rs doesn't exist, create a minimal version
                with open(os.path.join(td, "c2rust-lib.rs"), "w") as f:
                    f.write("#![allow(dead_code)]\n")
                    f.write("extern crate libc;\n")
                    f.write("pub mod main;\n")
            else:
                shutil.copy(lib_rs, td)
            
            # CRITICAL: Copy the source file as main.rs
            src_main_rs = os.path.join(td, "main.rs")
            shutil.copy(rs_file, src_main_rs)
            
            # Verify main.rs was created
            if not os.path.exists(src_main_rs):
                return False, []
            
            nightly = self.NIGHTLY
            tc_file = os.path.join(td, "rust-toolchain")
            if os.path.exists(tc_file):
                with open(tc_file) as f:
                    nightly = f.read().strip()
            
            # CRITICAL: Delete Cargo.lock and target to ensure fresh compilation
            cargo_lock = os.path.join(td, "Cargo.lock")
            if os.path.exists(cargo_lock):
                os.remove(cargo_lock)
            
            target_dir = os.path.join(td, "target")
            if os.path.exists(target_dir):
                shutil.rmtree(target_dir, ignore_errors=True)
            
            # Optimize compilation environment
            compile_env = {**os.environ, "RUSTFLAGS": "-Awarnings"}
            compile_env["CARGO_INCREMENTAL"] = "1"
            compile_env["RAYON_NUM_THREADS"] = "4"
            compile_env["CARGO_NET_RETRY"] = "3"
            
            result = subprocess.run(
                ["cargo", f"+{nightly}", "build", "--manifest-path",
                 os.path.join(td, "Cargo.toml")],
                capture_output=True, text=True, timeout=self.COMPILE_TIMEOUT,
                env=compile_env
            )
            
            if result.returncode == 0:
                return True, []
            else:
                errors = self.parse_compile_errors(result.stderr)
                return False, errors
        
        except subprocess.TimeoutExpired:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=f"Compilation timeout (>{self.COMPILE_TIMEOUT}s)",
                details=f"Compilation exceeded {self.COMPILE_TIMEOUT}s timeout."
            )]
        except Exception as e:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=str(e),
                details=str(e)[:300]
            )]
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    def try_compile_standalone(self, rs_file: str, example_dir: Optional[str] = None) -> Tuple[bool, List[ErrorInfo]]:
        """Try compiling a standalone .rs file."""
        td = tempfile.mkdtemp()
        try:
            # First try: standalone rustc
            compile_env = {**os.environ, "RUSTFLAGS": "-Awarnings"}
            compile_env["CARGO_INCREMENTAL"] = "1"
            
            result = subprocess.run(
                ["rustc", "--edition", "2021", rs_file,
                 "-o", os.path.join(td, "out")],
                capture_output=True, text=True, timeout=self.COMPILE_TIMEOUT,
                env=compile_env
            )
            
            if result.returncode == 0:
                return True, []
            
            # If standalone fails and we have example_dir, try cargo
            if example_dir and os.path.exists(example_dir):
                return self.try_compile_with_cargo(rs_file, example_dir)
            
            # Parse errors
            errors = self.parse_compile_errors(result.stderr)
            if not errors:
                errors = [ErrorInfo(
                    error_type="compile_error",
                    message="Compilation failed",
                    details=result.stderr[:500]
                )]
            return False, errors
        
        except subprocess.TimeoutExpired:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=f"Compilation timeout (>{self.COMPILE_TIMEOUT}s)",
                details="Compilation took too long"
            )]
        except Exception as e:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=str(e),
                details=str(e)[:300]
            )]
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    # ════════════════════════════════════════════════════════════════════════
    # Lock Safety Analysis
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def analyze_lock_safety(code: str, label: str = "code") -> Dict:
        """Analyze lock-related safety properties."""
        issues = []
        
        # Check for pthread remaining (bad in rewritten code)
        pthread_locks = re.findall(r'pthread_mutex_(lock|unlock|init|destroy)', code)
        if pthread_locks and label != "original":
            issues.append(f"Found {len(pthread_locks)} pthread_mutex calls (should use std::sync::Mutex)")
        
        # Check for manual lock/unlock without RAII (potential deadlock)
        if re.search(r'pthread_mutex_lock', code) and not re.search(r'pthread_mutex_unlock', code):
            issues.append("Found lock without unlock (potential deadlock)")
        if re.search(r'pthread_mutex_unlock', code) and not re.search(r'pthread_mutex_lock', code):
            issues.append("Found unlock without corresponding lock")
        
        # Check for static mut (data race risk)
        static_muts = re.findall(r'static\s+mut\s+(\w+)', code)
        if static_muts and label != "original":
            issues.append(f"Found {len(static_muts)} static mut variables (data race risk)")
        
        # Check for unsafe blocks
        unsafe_count = len(re.findall(r'\bunsafe\b', code))
        if unsafe_count > 0 and label != "original":
            issues.append(f"Found {unsafe_count} unsafe blocks")
        
        # Check for proper Arc<Mutex<T>> pattern
        has_arc_mutex = bool(re.search(r'Arc<\s*Mutex', code) or re.search(r'Arc::new\(\s*Mutex', code))
        
        # Check for proper thread joining
        has_thread_spawn = bool(re.search(r'thread::spawn', code))
        has_join = bool(re.search(r'\.join\(\)', code))
        if has_thread_spawn and not has_join:
            issues.append("Found thread::spawn without join (thread not waited)")
        
        return {
            "issues": issues,
            "has_std_mutex": bool(re.search(r'\bMutex\b', code)),
            "has_arc_mutex": has_arc_mutex,
            "has_pthread": bool(re.search(r'\bpthread_', code)),
            "has_thread_spawn": has_thread_spawn,
            "has_join": has_join,
            "unsafe_count": unsafe_count,
        }
    
    # ════════════════════════════════════════════════════════════════════════
    # Validation Methods
    # ════════════════════════════════════════════════════════════════════════
    
    def validate_compile(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate that code compiles."""
        success, errors = self.try_compile_standalone(rs_file, example_dir)
        if success:
            return ValidationResult(True, "compile", "Code compiles successfully", errors=[])
        else:
            error_summary = "\n".join([str(e) for e in errors[:3]])
            error_dicts = [e.to_dict() for e in errors]
            return ValidationResult(
                False, "compile", f"Compilation failed",
                details={"errors": error_dicts, "summary": error_summary},
                errors=errors
            )
    
    def validate_safety(self, code: str) -> ValidationResult:
        """Validate safety metrics."""
        metrics = self.safety_metrics(code)
        
        errors = []
        if metrics["unsafe"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['unsafe']} unsafe block(s) found",
                details=f"Unsafe blocks should be minimized. Found: {metrics['unsafe']}"
            ))
        if metrics["pthread"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['pthread']} pthread call(s) found",
                details=f"Rewritten code should use std::sync instead of pthread"
            ))
        if metrics["raw_ptr"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['raw_ptr']} raw pointer(s) found",
                details=f"Raw pointers are unsafe and should be minimized"
            ))
        if metrics["static_mut"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['static_mut']} static mut variable(s) found",
                details=f"Static mutable variables are data race risks"
            ))
        
        if errors:
            msg = f"Safety concerns: {len(errors)} issue(s)"
            return ValidationResult(False, "safety", msg, {"metrics": metrics}, errors=errors)
        else:
            return ValidationResult(True, "safety", "No major safety concerns", {"metrics": metrics}, errors=[])
    
    def validate_lock_safety(self, code: str) -> ValidationResult:
        """Validate lock safety."""
        analysis = self.analyze_lock_safety(code, label="rewritten")
        
        errors = []
        for issue in analysis["issues"]:
            errors.append(ErrorInfo(
                error_type="lock_safety_issue",
                message=issue,
                details=f"Lock safety analysis detected: {issue}"
            ))
        
        if errors:
            msg = f"Lock safety issues: {len(errors)} issue(s)"
            return ValidationResult(False, "lock_safety", msg, analysis, errors=errors)
        else:
            msg = "Lock safety OK"
            if analysis["has_std_mutex"]:
                msg += " (uses std::sync::Mutex)"
            if not analysis["has_pthread"]:
                msg += " (no pthread calls)"
            return ValidationResult(True, "lock_safety", msg, analysis, errors=[])
    
    def validate_clippy(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate code with clippy linter."""
        td = tempfile.mkdtemp()
        try:
            # Copy Cargo.toml and support files from the original example directory
            for f in ["Cargo.toml", "rust-toolchain"]:
                src = os.path.join(example_dir, f) if example_dir else None
                if src and os.path.exists(src):
                    shutil.copy(src, td)
            
            # Copy c2rust-lib.rs if available
            lib_rs = os.path.join(example_dir, "c2rust-lib.rs") if example_dir else None
            if lib_rs and os.path.exists(lib_rs):
                shutil.copy(lib_rs, td)
            else:
                with open(os.path.join(td, "c2rust-lib.rs"), "w") as f:
                    f.write("#![allow(dead_code)]\n")
                    f.write("extern crate libc;\n")
                    f.write("pub mod main;\n")
            
            # Copy the source file as main.rs
            src_main_rs = os.path.join(td, "main.rs")
            shutil.copy(rs_file, src_main_rs)
            
            nightly = self.NIGHTLY
            tc_file = os.path.join(td, "rust-toolchain")
            if os.path.exists(tc_file):
                with open(tc_file) as f:
                    nightly = f.read().strip()
            
            # Clean build artifacts
            cargo_lock = os.path.join(td, "Cargo.lock")
            if os.path.exists(cargo_lock):
                os.remove(cargo_lock)
            
            target_dir = os.path.join(td, "target")
            if os.path.exists(target_dir):
                shutil.rmtree(target_dir, ignore_errors=True)
            
            compile_env = {**os.environ, "RUSTFLAGS": "-Awarnings"}
            compile_env["CARGO_INCREMENTAL"] = "1"
            compile_env["RAYON_NUM_THREADS"] = "4"
            compile_env["CARGO_NET_RETRY"] = "3"
            
            result = subprocess.run(
                ["cargo", f"+{nightly}", "clippy", "--manifest-path",
                 os.path.join(td, "Cargo.toml"), "--", "-D", "warnings"],
                capture_output=True, text=True, timeout=self.COMPILE_TIMEOUT,
                env=compile_env
            )
            
            if result.returncode == 0:
                return ValidationResult(True, "clippy", "Clippy checks passed", errors=[])
            else:
                errors = self.parse_compile_errors(result.stderr)
                if not errors:
                    errors = [ErrorInfo(
                        error_type="clippy_error",
                        message="Clippy warnings found",
                        details=result.stderr[:1000]
                    )]
                return ValidationResult(False, "clippy", f"Clippy found {len(errors)} issue(s)", errors=errors)
        
        except subprocess.TimeoutExpired:
            return ValidationResult(
                False, "clippy",
                f"Clippy timeout (>{self.COMPILE_TIMEOUT}s)",
                errors=[ErrorInfo(
                    error_type="clippy_error",
                    message=f"Clippy timeout (>{self.COMPILE_TIMEOUT}s)",
                    details="Clippy analysis took too long"
                )]
            )
        except Exception as e:
            return ValidationResult(
                False, "clippy", str(e),
                errors=[ErrorInfo(
                    error_type="clippy_error",
                    message=str(e),
                    details=str(e)[:300]
                )]
            )
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    def validate_miri(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """
        Validate code with miri (detects UB at runtime).
        
        Uses cargo-nextest for parallel test execution (faster) if available,
        falls back to cargo miri test (slower) otherwise.
        
        Performance: nextest can be 3-5x faster due to parallelism
        Reference: https://github.com/rust-lang/miri/blob/master/README.md
        """
        td = tempfile.mkdtemp()
        try:
            # Copy Cargo.toml and support files
            for f in ["Cargo.toml", "rust-toolchain"]:
                src = os.path.join(example_dir, f) if example_dir else None
                if src and os.path.exists(src):
                    shutil.copy(src, td)
            
            # Copy c2rust-lib.rs if available
            lib_rs = os.path.join(example_dir, "c2rust-lib.rs") if example_dir else None
            if lib_rs and os.path.exists(lib_rs):
                shutil.copy(lib_rs, td)
            else:
                with open(os.path.join(td, "c2rust-lib.rs"), "w") as f:
                    f.write("#![allow(dead_code)]\n")
                    f.write("extern crate libc;\n")
                    f.write("pub mod main;\n")
            
            # Copy the source file as main.rs
            src_main_rs = os.path.join(td, "main.rs")
            shutil.copy(rs_file, src_main_rs)
            
            nightly = self.NIGHTLY
            tc_file = os.path.join(td, "rust-toolchain")
            if os.path.exists(tc_file):
                with open(tc_file) as f:
                    nightly = f.read().strip()
            
            # Clean build artifacts
            cargo_lock = os.path.join(td, "Cargo.lock")
            if os.path.exists(cargo_lock):
                os.remove(cargo_lock)
            
            target_dir = os.path.join(td, "target")
            if os.path.exists(target_dir):
                shutil.rmtree(target_dir, ignore_errors=True)
            
            compile_env = {**os.environ, "MIRIFLAGS": "-Zmiri-strict-provenance"}
            compile_env["CARGO_INCREMENTAL"] = "1"
            compile_env["RAYON_NUM_THREADS"] = "4"
            
            # Try nextest first (faster - parallelizes test runs)
            # Miri is single-threaded interpreter, but nextest wraps it to run tests in parallel
            has_nextest = False
            try:
                subprocess.run(
                    ["cargo", f"+{nightly}", "nextest", "--version"],
                    capture_output=True, timeout=5
                )
                has_nextest = True
            except (subprocess.TimeoutExpired, FileNotFoundError):
                has_nextest = False
            
            if has_nextest:
                # Use nextest for parallel execution (3-5x faster)
                result = subprocess.run(
                    ["cargo", f"+{nightly}", "miri", "nextest", "run", "-j4",
                     "--manifest-path", os.path.join(td, "Cargo.toml")],
                    capture_output=True, text=True, timeout=self.MIRI_TIMEOUT,
                    env=compile_env
                )
            else:
                # Fallback to cargo miri test (slower - single threaded)
                result = subprocess.run(
                    ["cargo", f"+{nightly}", "miri", "test", "--manifest-path",
                     os.path.join(td, "Cargo.toml")],
                    capture_output=True, text=True, timeout=self.MIRI_TIMEOUT,
                    env=compile_env
                )
            
            if result.returncode == 0:
                return ValidationResult(True, "miri", "Miri analysis passed (no UB detected)", errors=[])
            else:
                errors = self.parse_compile_errors(result.stderr)
                if not errors:
                    errors = [ErrorInfo(
                        error_type="miri_error",
                        message="Miri detected potential undefined behavior",
                        details=result.stderr[:1000]
                    )]
                
                error_summary = "\n".join([str(e) for e in errors[:3]])
                error_dicts = [e.to_dict() for e in errors]
                return ValidationResult(
                    False, "miri", f"Miri found {len(errors)} issue(s)",
                    details={"errors": error_dicts, "summary": error_summary},
                    errors=errors
                )
        
        except subprocess.TimeoutExpired:
            return ValidationResult(
                False, "miri",
                f"Miri timeout (>{self.MIRI_TIMEOUT}s)",
                errors=[ErrorInfo(
                    error_type="miri_error",
                    message=f"Miri timeout (>{self.MIRI_TIMEOUT}s)",
                    details="Miri analysis took too long (>30 minutes). This suggests infinite loops or very complex code patterns."
                )]
            )
        except Exception as e:
            return ValidationResult(
                False, "miri", str(e),
                errors=[ErrorInfo(
                    error_type="miri_error",
                    message=str(e),
                    details=str(e)[:300]
                )]
            )
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    def validate_loom(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """
        Validate code with loom (detects concurrency race conditions).
        
        Loom is a concurrency permutation testing tool that:
        - Runs tests many times with different thread scheduling permutations
        - Detects race conditions and data races under the C11 memory model
        - Uses state reduction to avoid combinatorial explosion
        
        Reference: https://github.com/tokio-rs/loom
        
        Performance: Very slow (can take 10+ minutes for complex code)
        """
        td = tempfile.mkdtemp()
        try:
            # Copy Cargo.toml and support files
            for f in ["Cargo.toml", "rust-toolchain"]:
                src = os.path.join(example_dir, f) if example_dir else None
                if src and os.path.exists(src):
                    shutil.copy(src, td)
            
            # Copy c2rust-lib.rs if available
            lib_rs = os.path.join(example_dir, "c2rust-lib.rs") if example_dir else None
            if lib_rs and os.path.exists(lib_rs):
                shutil.copy(lib_rs, td)
            else:
                with open(os.path.join(td, "c2rust-lib.rs"), "w") as f:
                    f.write("#![allow(dead_code)]\n")
                    f.write("extern crate libc;\n")
                    f.write("pub mod main;\n")
            
            # Copy the source file as main.rs
            src_main_rs = os.path.join(td, "main.rs")
            shutil.copy(rs_file, src_main_rs)
            
            # Update Cargo.toml to add loom as a conditional dependency
            cargo_toml_path = os.path.join(td, "Cargo.toml")
            if os.path.exists(cargo_toml_path):
                with open(cargo_toml_path, 'r') as f:
                    cargo_content = f.read()
                
                # Add loom dependency if not present
                if 'loom' not in cargo_content:
                    # Find the end of [dependencies] section
                    if '[dependencies]' in cargo_content:
                        cargo_content = cargo_content.replace(
                            '[dependencies]',
                            '[dependencies]\nloom = { version = "0.7", features = ["checkpoint"] }'
                        )
                    else:
                        cargo_content += '\n[dependencies]\nloom = { version = "0.7", features = ["checkpoint"] }\n'
                    
                    with open(cargo_toml_path, 'w') as f:
                        f.write(cargo_content)
            
            nightly = self.NIGHTLY
            tc_file = os.path.join(td, "rust-toolchain")
            if os.path.exists(tc_file):
                with open(tc_file) as f:
                    nightly = f.read().strip()
            
            # Clean build artifacts
            cargo_lock = os.path.join(td, "Cargo.lock")
            if os.path.exists(cargo_lock):
                os.remove(cargo_lock)
            
            target_dir = os.path.join(td, "target")
            if os.path.exists(target_dir):
                shutil.rmtree(target_dir, ignore_errors=True)
            
            compile_env = {**os.environ}
            compile_env["RUSTFLAGS"] = "--cfg loom -Awarnings"
            compile_env["CARGO_INCREMENTAL"] = "1"
            compile_env["RAYON_NUM_THREADS"] = "2"  # Limit to 2 threads since loom is very slow
            
            # Run loom tests with --release for better performance
            result = subprocess.run(
                ["cargo", f"+{nightly}", "test", "--test", "buggy*",
                 "--manifest-path", os.path.join(td, "Cargo.toml"), "--release"],
                capture_output=True, text=True, timeout=self.LOOM_TIMEOUT,
                env=compile_env
            )
            
            # Also try running with main
            if result.returncode != 0:
                result = subprocess.run(
                    ["cargo", f"+{nightly}", "test", "--bin", "main",
                     "--manifest-path", os.path.join(td, "Cargo.toml"), "--release"],
                    capture_output=True, text=True, timeout=self.LOOM_TIMEOUT,
                    env=compile_env
                )
            
            if result.returncode == 0:
                return ValidationResult(True, "loom", "Loom analysis passed (no race conditions detected)", errors=[])
            else:
                errors = self.parse_compile_errors(result.stderr)
                if not errors:
                    errors = [ErrorInfo(
                        error_type="loom_error",
                        message="Loom detected race conditions or test failures",
                        details=result.stderr[:1000]
                    )]
                return ValidationResult(False, "loom", f"Loom found issues", errors=errors)
        
        except subprocess.TimeoutExpired:
            return ValidationResult(
                False, "loom",
                f"Loom timeout (>{self.LOOM_TIMEOUT}s)",
                errors=[ErrorInfo(
                    error_type="loom_error",
                    message=f"Loom timeout (>{self.LOOM_TIMEOUT}s)",
                    details="Loom analysis took too long (>60 minutes). This suggests very complex concurrent code or infinite loops in a test scenario. The code may need simplification for loom testing."
                )]
            )
        except Exception as e:
            return ValidationResult(
                False, "loom", str(e),
                errors=[ErrorInfo(
                    error_type="loom_error",
                    message=str(e),
                    details=str(e)[:300]
                )]
            )
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    def validate(self, rs_file: str, code: str, tools: Optional[List[str]] = None,
                 example_dir: Optional[str] = None) -> List[ValidationResult]:
        """
        Run validation on code with specified tools.
        
        Args:
            rs_file: Path to .rs file (needed for compile check)
            code: Source code (needed for safety checks)
            tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
                   Tools can be combined. If None, defaults to ['compile']
            example_dir: Path to example directory (optional, for cargo context)
        
        Returns:
            List of ValidationResult objects
        """
        if tools is None:
            tools = ["compile"]
        
        results = []
        
        # Map tool names to validation methods
        tool_map = {
            "compile": lambda: self.validate_compile(rs_file, example_dir),
            "clippy": lambda: self.validate_clippy(rs_file, example_dir),
            "miri": lambda: self.validate_miri(rs_file, example_dir),
            "loom": lambda: self.validate_loom(rs_file, example_dir),
            "safety": lambda: self.validate_safety(code),
            "lock_safety": lambda: self.validate_lock_safety(code),
        }
        
        # Handle special cases
        if "comprehensive" in tools:
            tools = ["compile", "clippy", "safety", "lock_safety"]
        
        # Run each tool
        for tool in tools:
            tool = tool.lower().strip()
            if tool in tool_map:
                results.append(tool_map[tool]())
        
        return results
    
    def validate_and_report(self, rs_file: str, code: str, tools: Optional[List[str]] = None,
                           example_dir: Optional[str] = None) -> Tuple[bool, str, List[ValidationResult]]:
        """
        Run validation and generate a report.
        
        Args:
            rs_file: Path to .rs file
            code: Source code
            tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
            example_dir: Path to example directory (optional)
        
        Returns:
            (all_passed: bool, report_text: str, results: List[ValidationResult])
        """
        results = self.validate(rs_file, code, tools, example_dir)
        
        report_lines = []
        all_passed = all(r.passed for r in results) if results else True
        
        for r in results:
            status = "✅" if r.passed else "❌"
            report_lines.append(f"{status} [{r.category}] {r.message}")
        
        report = "\n".join(report_lines)
        return all_passed, report, results


def validate_file(rs_file: str, tools: Optional[List[str]] = None, example_dir: Optional[str] = None) -> Tuple[bool, str]:
    """
    Quick validation of a single file.
    
    Args:
        rs_file: Path to .rs file
        tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
               Tools can be combined. If None, defaults to ['compile']
        example_dir: Path to example directory (for cargo context)
    
    Returns:
        (passed: bool, report: str)
    """
    if tools is None:
        tools = ["compile"]
    
    validator = CodeValidator()
    
    with open(rs_file) as f:
        code = f.read()
    
    passed, report, _ = validator.validate_and_report(rs_file, code, tools, example_dir)
    return passed, report
