#!/usr/bin/env python3
"""
Core validator orchestrator.

Coordinates all validation tools and provides unified API.
"""

from typing import Dict, List, Tuple, Optional
from .errors import ErrorInfo, ValidationResult
from .compile import CompileValidator
from .clippy import ClippyValidator
from .miri import MiriValidator
from .loom import LoomValidator
from .safety import SafetyAnalyzer


class CodeValidator:
    """Validator for Rust code generated by refactor."""
    
    NIGHTLY = "nightly"
    
    def __init__(self, deps_dir: Optional[str] = None):
        """
        Initialize validator.
        
        Args:
            deps_dir: Path to compiled dependencies (optional)
        """
        self.deps_dir = deps_dir or "/home/guoxy/concrat/deps_crate/target/debug/deps"
    
    def validate_compile(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate that code compiles (delegates to CompileValidator)."""
        return CompileValidator.validate_compile(rs_file, example_dir, self.NIGHTLY)
    
    def validate_clippy(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate code with clippy linter (delegates to ClippyValidator)."""
        return ClippyValidator.validate_clippy(rs_file, example_dir, self.NIGHTLY)
    
    def validate_miri(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate code with miri (delegates to MiriValidator)."""
        return MiriValidator.validate_miri(rs_file, example_dir, self.NIGHTLY)
    
    def validate_loom(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate code with loom (delegates to LoomValidator)."""
        return LoomValidator.validate_loom(rs_file, example_dir, self.NIGHTLY)
    
    def validate_safety(self, code: str) -> ValidationResult:
        """Validate safety metrics (delegates to SafetyAnalyzer)."""
        return SafetyAnalyzer.validate_safety(code)
    
    def validate_lock_safety(self, code: str) -> ValidationResult:
        """Validate lock safety (delegates to SafetyAnalyzer)."""
        return SafetyAnalyzer.validate_lock_safety(code)
    
    def try_compile_standalone(self, rs_file: str, example_dir: Optional[str] = None) -> Tuple[bool, List[ErrorInfo]]:
        """
        Try compiling a standalone .rs file (for backward compatibility).
        
        Args:
            rs_file: Path to .rs file
            example_dir: Path to example directory (optional)
        
        Returns:
            (success: bool, errors: List[ErrorInfo])
        """
        return CompileValidator.try_compile_standalone(rs_file, example_dir, self.NIGHTLY)
    
    def try_compile_with_cargo(self, rs_file: str, example_dir: str) -> Tuple[bool, List[ErrorInfo]]:
        """
        Try compiling with cargo.toml context (for backward compatibility).
        
        Args:
            rs_file: Path to .rs file
            example_dir: Path to example directory with Cargo.toml
        
        Returns:
            (success: bool, errors: List[ErrorInfo])
        """
        return CompileValidator.try_compile_with_cargo(rs_file, example_dir, self.NIGHTLY)
    
    def validate(self, rs_file: str, code: str, tools: Optional[List[str]] = None,
                 example_dir: Optional[str] = None) -> List[ValidationResult]:
        """
        Run validation on code with specified tools.
        
        Args:
            rs_file: Path to .rs file (needed for compile check)
            code: Source code (needed for safety checks)
            tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
                   Tools can be combined. If None, defaults to ['compile']
            example_dir: Path to example directory (optional, for cargo context)
        
        Returns:
            List of ValidationResult objects
        """
        if tools is None:
            tools = ["compile"]
        
        results = []
        
        # Map tool names to validation methods
        tool_map = {
            "compile": lambda: self.validate_compile(rs_file, example_dir),
            "clippy": lambda: self.validate_clippy(rs_file, example_dir),
            "miri": lambda: self.validate_miri(rs_file, example_dir),
            "loom": lambda: self.validate_loom(rs_file, example_dir),
            "safety": lambda: self.validate_safety(code),
            "lock_safety": lambda: self.validate_lock_safety(code),
        }
        
        # Handle special cases
        if "comprehensive" in tools:
            tools = ["compile", "clippy", "safety", "lock_safety"]
        
        # Run each tool
        for tool in tools:
            tool = tool.lower().strip()
            if tool in tool_map:
                results.append(tool_map[tool]())
        
        return results
    
    def validate_and_report(self, rs_file: str, code: str, tools: Optional[List[str]] = None,
                           example_dir: Optional[str] = None) -> Tuple[bool, str, List[ValidationResult]]:
        """
        Run validation and generate a report.
        
        Args:
            rs_file: Path to .rs file
            code: Source code
            tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
            example_dir: Path to example directory (optional)
        
        Returns:
            (all_passed: bool, report_text: str, results: List[ValidationResult])
        """
        results = self.validate(rs_file, code, tools, example_dir)
        
        report_lines = []
        all_passed = all(r.passed for r in results) if results else True
        
        for r in results:
            status = "✅" if r.passed else "❌"
            report_lines.append(f"{status} [{r.category}] {r.message}")
        
        report = "\n".join(report_lines)
        return all_passed, report, results


def validate_file(rs_file: str, tools: Optional[List[str]] = None, example_dir: Optional[str] = None) -> Tuple[bool, str]:
    """
    Quick validation of a single file.
    
    Args:
        rs_file: Path to .rs file
        tools: List of tools to run (e.g., ['compile', 'clippy', 'miri'])
               Tools can be combined. If None, defaults to ['compile']
        example_dir: Path to example directory (for cargo context)
    
    Returns:
        (passed: bool, report: str)
    """
    if tools is None:
        tools = ["compile"]
    
    validator = CodeValidator()
    
    with open(rs_file) as f:
        code = f.read()
    
    passed, report, _ = validator.validate_and_report(rs_file, code, tools, example_dir)
    return passed, report
