#!/usr/bin/env python3
"""
Validator module for validating LLM-rewritten Rust code.

Provides multiple validation strategies:
  - compile: Check if code compiles
  - safety: Check for unsafe patterns
  - lock_safety: Check lock usage patterns
  - comprehensive: All checks combined
"""

import os
import re
import subprocess
import tempfile
import shutil
from typing import Dict, List, Tuple, Optional
from enum import Enum


class ValidationStrategy(Enum):
    """Available validation strategies."""
    COMPILE = "compile"
    SAFETY = "safety"
    LOCK_SAFETY = "lock_safety"
    COMPREHENSIVE = "comprehensive"


class ErrorInfo:
    """Structured error information."""
    
    def __init__(self, error_type: str, message: str, location: str = "", 
                 error_code: str = "", line: int = -1, column: int = -1, details: str = ""):
        """
        Args:
            error_type: "compile_error", "safety_issue", "lock_safety_issue", etc.
            message: Human-readable error message
            location: File location (e.g., "src/main.rs:5:21")
            error_code: Error code (e.g., "E0425")
            line: Line number (-1 if unknown)
            column: Column number (-1 if unknown)
            details: Full error details or additional context
        """
        self.error_type = error_type
        self.message = message
        self.location = location
        self.error_code = error_code
        self.line = line
        self.column = column
        self.details = details
    
    def to_dict(self):
        """Convert to dictionary for serialization."""
        return {
            "type": self.error_type,
            "code": self.error_code,
            "message": self.message,
            "location": self.location,
            "line": self.line,
            "column": self.column,
            "details": self.details[:500] if self.details else ""  # Truncate for JSON
        }
    
    def __repr__(self):
        loc_str = f" [{self.location}]" if self.location else ""
        code_str = f" ({self.error_code})" if self.error_code else ""
        return f"{self.message}{code_str}{loc_str}"


class ValidationResult:
    """Result of a validation check."""
    
    def __init__(self, passed: bool, category: str, message: str = "", details: Dict = None, errors: List[ErrorInfo] = None):
        self.passed = passed
        self.category = category
        self.message = message
        self.details = details or {}
        self.errors = errors or []  # List of structured ErrorInfo
    
    def __repr__(self):
        status = "✅" if self.passed else "❌"
        return f"{status} [{self.category}] {self.message}"


class CodeValidator:
    """Validator for Rust code generated by refactor."""
    
    NIGHTLY = "nightly-2022-07-05"
    
    # Regex patterns for parsing Rust compiler errors
    ERROR_PATTERN = re.compile(
        r'error(?:\[([^\]]+)\])?: (.+?)(?:\n\s*-->\s*(.+?):\s*(\d+):(\d+))?',
        re.MULTILINE
    )
    # Pattern: error[CODE]: message --> file:line:col
    
    def __init__(self, deps_dir: Optional[str] = None):
        """
        Initialize validator.
        
        Args:
            deps_dir: Path to compiled dependencies (optional)
        """
        self.deps_dir = deps_dir or "/home/guoxy/concrat/deps_crate/target/debug/deps"
    
    # ════════════════════════════════════════════════════════════════════════
    # Error Parsing
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def parse_compile_errors(stderr: str) -> List[ErrorInfo]:
        """
        Parse Rust compiler errors from stderr into structured ErrorInfo objects.
        
        Handles formats like:
            error[E0425]: cannot find value `x` in this scope
             --> src/main.rs:5:21
        
        Returns:
            List of ErrorInfo objects
        """
        errors = []
        
        # Split by "error" lines and process each
        lines = stderr.split('\n')
        i = 0
        while i < len(lines):
            line = lines[i]
            
            if line.startswith('error'):
                # Parse error header: "error[CODE]: message"
                match = re.match(r'error(?:\[([^\]]+)\])?: (.+)', line)
                if match:
                    error_code = match.group(1) or ""
                    message = match.group(2).strip()
                    
                    # Look for location in next line: " --> file:line:col"
                    location = ""
                    file_path = ""
                    line_num = -1
                    col_num = -1
                    
                    if i + 1 < len(lines):
                        loc_line = lines[i + 1]
                        loc_match = re.search(r'-->\s*(.+?):(\d+):(\d+)', loc_line)
                        if loc_match:
                            file_path = loc_match.group(1).strip()
                            line_num = int(loc_match.group(2))
                            col_num = int(loc_match.group(3))
                            location = f"{file_path}:{line_num}:{col_num}"
                    
                    error_info = ErrorInfo(
                        error_type="compile_error",
                        error_code=error_code,
                        message=message,
                        location=location,
                        line=line_num,
                        column=col_num,
                        details=stderr[:1000]  # Store first 1000 chars of full stderr
                    )
                    errors.append(error_info)
            
            i += 1
        
        return errors
    
    # ════════════════════════════════════════════════════════════════════════
    # Safety Metrics
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def count_pattern(code: str, pattern: str) -> int:
        """Count occurrences of a regex pattern in code."""
        return len(re.findall(pattern, code))
    
    @staticmethod
    def safety_metrics(code: str) -> Dict[str, int]:
        """Extract safety metrics from code."""
        return {
            "unsafe":       CodeValidator.count_pattern(code, r'\bunsafe\b'),
            "pthread":      CodeValidator.count_pattern(code, r'\bpthread_'),
            "raw_ptr":      CodeValidator.count_pattern(code, r'\*mut\b|\*const\b'),
            "static_mut":   CodeValidator.count_pattern(code, r'\bstatic\s+mut\b'),
            "libc":         CodeValidator.count_pattern(code, r'\blibc::'),
            "std_mutex":    CodeValidator.count_pattern(code, r'\bMutex\b'),
            "std_arc":      CodeValidator.count_pattern(code, r'\bArc\b'),
            "std_rwlock":   CodeValidator.count_pattern(code, r'\bRwLock\b'),
            "std_condvar":  CodeValidator.count_pattern(code, r'\bCondvar\b'),
            "std_thread":   CodeValidator.count_pattern(code, r'\bthread::spawn\b'),
            "lines":        len(code.splitlines()),
        }
    
    # ════════════════════════════════════════════════════════════════════════
    # Compilation Check
    # ════════════════════════════════════════════════════════════════════════
    
    def try_compile_with_cargo(self, rs_file: str, example_dir: str) -> Tuple[bool, List[ErrorInfo]]:
        """
        Try compiling a .rs file using the example's Cargo.toml context.
        
        Returns:
            (success: bool, errors: List[ErrorInfo])
        """
        td = tempfile.mkdtemp()
        try:
            # Copy Cargo.toml and support files
            for f in ["Cargo.toml", "rust-toolchain"]:
                src = os.path.join(example_dir, f)
                if os.path.exists(src):
                    shutil.copy(src, td)
            
            # Copy c2rust-lib.rs if exists
            lib_rs = os.path.join(example_dir, "c2rust-lib.rs")
            if os.path.exists(lib_rs):
                shutil.copy(lib_rs, td)
            
            # Copy the target file as main.c2rust.rs
            shutil.copy(rs_file, os.path.join(td, "main.c2rust.rs"))
            
            nightly = self.NIGHTLY
            tc_file = os.path.join(td, "rust-toolchain")
            if os.path.exists(tc_file):
                with open(tc_file) as f:
                    nightly = f.read().strip()
            
            result = subprocess.run(
                ["cargo", f"+{nightly}", "build", "--manifest-path",
                 os.path.join(td, "Cargo.toml")],
                capture_output=True, text=True, timeout=60,
                env={**os.environ, "RUSTFLAGS": "-Awarnings"}
            )
            
            if result.returncode == 0:
                return True, []
            else:
                # Parse structured errors
                errors = self.parse_compile_errors(result.stderr)
                # If no structured errors found, create a generic one
                if not errors:
                    errors = [ErrorInfo(
                        error_type="compile_error",
                        message="Compilation failed",
                        details=result.stderr[:500]
                    )]
                return False, errors
        
        except subprocess.TimeoutExpired:
            return False, [ErrorInfo(
                error_type="compile_error",
                message="Compilation timeout",
                details="Compilation exceeded 120s timeout"
            )]
        except Exception as e:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=str(e),
                details=str(e)[:300]
            )]
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    def try_compile_standalone(self, rs_file: str, example_dir: Optional[str] = None) -> Tuple[bool, List[ErrorInfo]]:
        """
        Try compiling a standalone .rs file.
        Falls back to Cargo if standalone rustc fails.
        
        Returns:
            (success: bool, errors: List[ErrorInfo])
        """
        td = tempfile.mkdtemp()
        try:
            # First try: standalone rustc (for LLM-generated code)
            result = subprocess.run(
                ["rustc", "--edition", "2021", rs_file,
                 "-o", os.path.join(td, "out")],
                capture_output=True, text=True, timeout=60,
                env={**os.environ, "RUSTFLAGS": "-Awarnings"}
            )
            
            if result.returncode == 0:
                return True, []
            
            # If standalone fails and we have example_dir, try cargo
            if example_dir and os.path.exists(example_dir):
                return self.try_compile_with_cargo(rs_file, example_dir)
            
            # Parse structured errors
            errors = self.parse_compile_errors(result.stderr)
            if not errors:
                errors = [ErrorInfo(
                    error_type="compile_error",
                    message="Compilation failed",
                    details=result.stderr[:500]
                )]
            return False, errors
        
        except subprocess.TimeoutExpired:
            return False, [ErrorInfo(
                error_type="compile_error",
                message="Compilation timeout",
                details="Compilation exceeded 120s timeout"
            )]
        except Exception as e:
            return False, [ErrorInfo(
                error_type="compile_error",
                message=str(e),
                details=str(e)[:300]
            )]
        finally:
            shutil.rmtree(td, ignore_errors=True)
    
    # ════════════════════════════════════════════════════════════════════════
    # Lock Safety Analysis
    # ════════════════════════════════════════════════════════════════════════
    
    @staticmethod
    def analyze_lock_safety(code: str, label: str = "code") -> Dict:
        """
        Analyze lock-related safety properties.
        
        Args:
            code: Rust code to analyze
            label: Label for the code (e.g., "original", "rewritten")
        
        Returns:
            Dictionary with lock safety analysis
        """
        issues = []
        
        # Check for pthread remaining (bad in rewritten code)
        pthread_locks = re.findall(r'pthread_mutex_(lock|unlock|init|destroy)', code)
        if pthread_locks and label != "original":
            issues.append(f"Still uses pthread_mutex ({len(pthread_locks)} calls)")
        
        # Check for manual lock/unlock without RAII (potential deadlock)
        if re.search(r'pthread_mutex_lock', code) and not re.search(r'pthread_mutex_unlock', code):
            issues.append("Lock without matching unlock (potential deadlock)")
        if re.search(r'pthread_mutex_unlock', code) and not re.search(r'pthread_mutex_lock', code):
            issues.append("Unlock without matching lock")
        
        # Check for static mut (data race risk)
        static_muts = re.findall(r'static\s+mut\s+(\w+)', code)
        if static_muts and label != "original":
            issues.append(f"static mut variables remain: {', '.join(static_muts[:5])}")
        
        # Check for unsafe blocks
        unsafe_count = len(re.findall(r'\bunsafe\b', code))
        if unsafe_count > 0 and label != "original":
            issues.append(f"{unsafe_count} unsafe keyword(s) remain")
        
        # Check for proper Arc<Mutex<T>> pattern
        has_arc_mutex = bool(re.search(r'Arc<\s*Mutex', code) or re.search(r'Arc::new\(\s*Mutex', code))
        
        # Check for proper thread joining
        has_thread_spawn = bool(re.search(r'thread::spawn', code))
        has_join = bool(re.search(r'\.join\(\)', code))
        if has_thread_spawn and not has_join:
            issues.append("thread::spawn without join (detached thread)")
        
        return {
            "issues": issues,
            "has_std_mutex": bool(re.search(r'\bMutex\b', code)),
            "has_arc_mutex": has_arc_mutex,
            "has_pthread": bool(re.search(r'\bpthread_', code)),
            "has_thread_spawn": has_thread_spawn,
            "has_join": has_join,
            "unsafe_count": unsafe_count,
        }
    
    # ════════════════════════════════════════════════════════════════════════
    # Validation Methods
    # ════════════════════════════════════════════════════════════════════════
    
    def validate_compile(self, rs_file: str, example_dir: Optional[str] = None) -> ValidationResult:
        """Validate that code compiles."""
        success, errors = self.try_compile_standalone(rs_file, example_dir)
        if success:
            return ValidationResult(True, "compile", "Code compiles successfully", errors=[])
        else:
            # Create error message summary from ErrorInfo objects
            error_summary = "\n".join([str(e) for e in errors[:3]])  # Show first 3 errors
            error_dicts = [e.to_dict() for e in errors]
            return ValidationResult(
                False, 
                "compile", 
                f"Compilation failed",
                details={"errors": error_dicts, "summary": error_summary},
                errors=errors
            )
    
    def validate_safety(self, code: str) -> ValidationResult:
        """Validate safety metrics."""
        metrics = self.safety_metrics(code)
        
        errors = []
        if metrics["unsafe"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['unsafe']} unsafe block(s) found",
                details=f"Unsafe blocks should be minimized. Found: {metrics['unsafe']}"
            ))
        if metrics["pthread"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['pthread']} pthread call(s) found",
                details=f"Rewritten code should use std::sync instead of pthread"
            ))
        if metrics["raw_ptr"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['raw_ptr']} raw pointer(s) found",
                details=f"Raw pointers are unsafe and should be minimized"
            ))
        if metrics["static_mut"] > 0:
            errors.append(ErrorInfo(
                error_type="safety_issue",
                message=f"{metrics['static_mut']} static mut variable(s) found",
                details=f"Static mutable variables are data race risks"
            ))
        
        if errors:
            msg = f"Safety concerns: {len(errors)} issue(s)"
            return ValidationResult(False, "safety", msg, {"metrics": metrics}, errors=errors)
        else:
            return ValidationResult(True, "safety", "No major safety concerns", {"metrics": metrics}, errors=[])
    
    def validate_lock_safety(self, code: str) -> ValidationResult:
        """Validate lock safety."""
        analysis = self.analyze_lock_safety(code, label="rewritten")
        
        errors = []
        for issue in analysis["issues"]:
            errors.append(ErrorInfo(
                error_type="lock_safety_issue",
                message=issue,
                details=f"Lock safety analysis detected: {issue}"
            ))
        
        if errors:
            msg = f"Lock safety issues: {len(errors)} issue(s)"
            return ValidationResult(False, "lock_safety", msg, analysis, errors=errors)
        else:
            msg = "Lock safety OK"
            if analysis["has_std_mutex"]:
                msg += " (uses std::sync::Mutex)"
            if not analysis["has_pthread"]:
                msg += " (no pthread)"
            return ValidationResult(True, "lock_safety", msg, analysis, errors=[])
    
    def validate(self, rs_file: str, code: str, strategy: ValidationStrategy = ValidationStrategy.COMPILE,
                 example_dir: Optional[str] = None) -> List[ValidationResult]:
        """
        Run validation on code.
        
        Args:
            rs_file: Path to .rs file (needed for compile check)
            code: Source code (needed for safety checks)
            strategy: What to validate
            example_dir: Path to example directory (optional, for cargo context)
        
        Returns:
            List of ValidationResult objects
        """
        results = []
        
        if strategy in (ValidationStrategy.COMPILE, ValidationStrategy.COMPREHENSIVE):
            results.append(self.validate_compile(rs_file, example_dir))
        
        if strategy in (ValidationStrategy.SAFETY, ValidationStrategy.COMPREHENSIVE):
            results.append(self.validate_safety(code))
        
        if strategy in (ValidationStrategy.LOCK_SAFETY, ValidationStrategy.COMPREHENSIVE):
            results.append(self.validate_lock_safety(code))
        
        return results
    
    def validate_and_report(self, rs_file: str, code: str, strategy: ValidationStrategy = ValidationStrategy.COMPILE,
                           example_dir: Optional[str] = None) -> Tuple[bool, str, List[ValidationResult]]:
        """
        Run validation and generate a report.
        
        Returns:
            (all_passed: bool, report_text: str, results: List[ValidationResult])
        """
        results = self.validate(rs_file, code, strategy, example_dir)
        
        report_lines = []
        all_passed = all(r.passed for r in results)
        
        for r in results:
            status = "✅" if r.passed else "❌"
            report_lines.append(f"{status} [{r.category}] {r.message}")
        
        report = "\n".join(report_lines)
        return all_passed, report, results


# ────────────────────────────────────────────────────────────────────────────
# Helper functions
# ────────────────────────────────────────────────────────────────────────────

def validate_file(rs_file: str, strategy: str = "compile", example_dir: Optional[str] = None) -> Tuple[bool, str]:
    """
    Quick validation of a single file.
    
    Args:
        rs_file: Path to .rs file
        strategy: "compile", "safety", "lock_safety", or "comprehensive"
        example_dir: Path to example directory (for cargo context)
    
    Returns:
        (passed: bool, report: str)
    """
    try:
        strat = ValidationStrategy(strategy)
    except ValueError:
        return False, f"Unknown strategy: {strategy}"
    
    validator = CodeValidator()
    
    with open(rs_file) as f:
        code = f.read()
    
    passed, report, _ = validator.validate_and_report(rs_file, code, strat, example_dir)
    return passed, report


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python validator.py <rs_file> [strategy] [example_dir]")
        print("Strategies: compile, safety, lock_safety, comprehensive")
        sys.exit(1)
    
    rs_file = sys.argv[1]
    strategy = sys.argv[2] if len(sys.argv) > 2 else "compile"
    example_dir = sys.argv[3] if len(sys.argv) > 3 else None
    
    passed, report = validate_file(rs_file, strategy, example_dir)
    print(report)
    sys.exit(0 if passed else 1)
