#!/bin/bash

# ════════════════════════════════════════════════════════════════════════════
# Regenerate C2Rust translations for all examples_negative directories
# ════════════════════════════════════════════════════════════════════════════
#
# This script will:
#   1. For each directory in examples_negative/
#   2. Run c2rust transpile on a.c to generate Rust code
#   3. Rename the generated a.rs to main.c2rust.rs (the c2rust translation)
#   4. Ensure c2rust-lib.rs is properly set up
#
# Usage:
#   ./scripts/regenerate_negative_examples.sh
#   ./scripts/regenerate_negative_examples.sh --force     # Ignore existing main.c2rust.rs
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
C2RUST_BIN="${C2RUST_BIN:=/home/guoxy/c2rust/target/release/c2rust}"
EXAMPLES_NEG_DIR="$PROJECT_DIR/examples_negative"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'  # No Color

# Parse arguments
FORCE_REGENERATE=false
for arg in "$@"; do
    case "$arg" in
        --force)
            FORCE_REGENERATE=true
            ;;
        *)
            echo "Unknown argument: $arg"
            exit 1
            ;;
    esac
done

# Check if c2rust is available
if [ ! -x "$C2RUST_BIN" ]; then
    echo -e "${RED}❌ Error: c2rust binary not found at $C2RUST_BIN${NC}"
    echo "   Please set C2RUST_BIN environment variable or install c2rust"
    exit 1
fi

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  Regenerating C2Rust Translations for examples_negative       ║${NC}"
echo -e "${BLUE}║  Output: main.c2rust.rs (C2Rust translation output)                  ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [ ! -d "$EXAMPLES_NEG_DIR" ]; then
    echo -e "${RED}❌ Error: $EXAMPLES_NEG_DIR not found${NC}"
    exit 1
fi

# Statistics
TOTAL=0
SUCCESS=0
SKIPPED=0
FAILED=0

# Process each directory in examples_negative
for dir in "$EXAMPLES_NEG_DIR"/*; do
    if [ -d "$dir" ]; then
        DIR_NAME=$(basename "$dir")
        TOTAL=$((TOTAL + 1))
        
        # Check if a.c exists
        if [ ! -f "$dir/a.c" ]; then
            echo -e "${YELLOW}⊘ SKIP ${DIR_NAME}${NC}: No a.c found"
            SKIPPED=$((SKIPPED + 1))
            continue
        fi
        
        # Check if main.c2rust.rs already exists (unless --force)
        if [ -f "$dir/main.c2rust.rs" ] && [ "$FORCE_REGENERATE" = "false" ]; then
            echo -e "${YELLOW}⊘ SKIP ${DIR_NAME}${NC}: main.c2rust.rs already exists (use --force to regenerate)"
            SKIPPED=$((SKIPPED + 1))
            continue
        fi
        
        echo -n "Processing ${DIR_NAME}... "
        
        cd "$dir" || exit 1
        
        # Clean up old files (keep backups)
        rm -f compile_commands.json a.rs main.c2rust.rs.bak
        [ -f main.c2rust.rs ] && cp main.c2rust.rs main.c2rust.rs.bak
        
        # Generate compile_commands.json
        # Using a.c as the source file; c2rust will generate a.rs
        echo "[{\"arguments\":[\"cc\",\"-c\",\"-pthread\",\"-o\",\"main.o\",\"a.c\"],\"directory\":\"$(pwd)\",\"file\":\"a.c\"}]" > compile_commands.json
        
        # Run c2rust transpile
        if ! "$C2RUST_BIN" transpile -e compile_commands.json > c2rust_transpile.log 2>&1; then
            echo -e "${RED}❌ FAILED${NC}"
            echo "   Error: c2rust transpile failed"
            cat c2rust_transpile.log | head -10 | sed 's/^/   /'
            FAILED=$((FAILED + 1))
            cd "$PROJECT_DIR" || exit 1
            continue
        fi
        
        # Check if a.rs was generated
        if [ ! -f a.rs ]; then
            echo -e "${RED}❌ FAILED${NC}"
            echo "   Error: No a.rs generated by c2rust"
            FAILED=$((FAILED + 1))
            cd "$PROJECT_DIR" || exit 1
            continue
        fi
        
        # Rename a.rs to main.c2rust.rs (the C2Rust translation output)
        mv a.rs main.c2rust.rs
        
        # Verify main.c2rust.rs is not empty
        if [ ! -s main.c2rust.rs ]; then
            echo -e "${RED}❌ FAILED${NC}"
            echo "   Error: Generated main.c2rust.rs is empty"
            FAILED=$((FAILED + 1))
            # Restore backup if exists
            [ -f main.c2rust.rs.bak ] && mv main.c2rust.rs.bak main.c2rust.rs
            cd "$PROJECT_DIR" || exit 1
            continue
        fi
        
        # Ensure c2rust-lib.rs has proper module declaration
        # (should already exist, but verify it has 'pub mod main;')
        if [ ! -f c2rust-lib.rs ]; then
            echo -e "${RED}❌ FAILED${NC}"
            echo "   Error: c2rust-lib.rs missing"
            FAILED=$((FAILED + 1))
            cd "$PROJECT_DIR" || exit 1
            continue
        fi
        
        if ! grep -q "pub mod main" c2rust-lib.rs; then
            echo -e "${RED}❌ FAILED${NC}"
            echo "   Error: c2rust-lib.rs doesn't declare 'pub mod main'"
            FAILED=$((FAILED + 1))
            cd "$PROJECT_DIR" || exit 1
            continue
        fi
        
        # Clean up temporary files
        rm -f compile_commands.json c2rust_transpile.log main.c2rust.rs.bak
        
        echo -e "${GREEN}✅ SUCCESS${NC}"
        SUCCESS=$((SUCCESS + 1))
        
        cd "$PROJECT_DIR" || exit 1
    fi
done

echo ""
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo "Summary:"
echo "  Total directories:     $TOTAL"
echo -e "  ${GREEN}Successfully generated${NC}: $SUCCESS"
echo -e "  ${YELLOW}Skipped${NC}:                $SKIPPED"
echo -e "  ${RED}Failed${NC}:                 $FAILED"
echo -e "${BLUE}════════════════════════════════════════════════════════════════${NC}"
echo ""

if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}✅ All examples processed successfully!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Verify generated main.c2rust.rs files:"
    echo "     ls examples_negative/*/main.c2rust.rs"
    echo "  2. Test the examples:"
    echo "     ./scripts/test_negative_examples.sh"
    exit 0
else
    echo -e "${RED}❌ Some examples failed to process${NC}"
    exit 1
fi
